project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Socioeconomic Analysis in Peru"
  author:
    - Lady Infante Acosta (ldi2101)
    - Viviana Hanampa Castillo (vsh2108)
  repo-url: https://github.com/LadyInfanteA/peru-socioeconomic-analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


